#!/usr/bin/env python3
"""
Cloud Processor - Automated Draft Generation
Processes tasks from Needs_Action and creates drafts in Pending_Approval
"""

import os
import sys
import shutil
from pathlib import Path
from datetime import datetime
import time

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

VAULT = Path("AI_Employee_Vault")
NEEDS_ACTION_EMAIL = VAULT / "Needs_Action" / "email"
NEEDS_ACTION_SOCIAL = VAULT / "Needs_Action" / "social"
IN_PROGRESS_CLOUD = VAULT / "In_Progress" / "cloud"
PENDING_APPROVAL_EMAIL = VAULT / "Pending_Approval" / "email"
PENDING_APPROVAL_SOCIAL = VAULT / "Pending_Approval" / "social"
DONE = VAULT / "Done"
FAILED_CLOUD = VAULT / "Failed" / "cloud"

# Ensure directories exist
for dir_path in [NEEDS_ACTION_EMAIL, NEEDS_ACTION_SOCIAL, IN_PROGRESS_CLOUD,
                 PENDING_APPROVAL_EMAIL, PENDING_APPROVAL_SOCIAL, DONE, FAILED_CLOUD]:
    dir_path.mkdir(parents=True, exist_ok=True)


def claim_task(task_file, claimed_dir):
    """
    Claim task by moving to In_Progress/cloud
    Returns claimed path or None if already claimed
    """
    task_name = task_file.name
    claimed_path = claimed_dir / task_name

    try:
        shutil.move(str(task_file), str(claimed_path))
        print(f"✅ Claimed: {task_name}")
        return claimed_path
    except FileNotFoundError:
        print(f"⚠️  Already claimed: {task_name}")
        return None


def generate_email_draft(task_content):
    """Generate AI-powered email draft"""
    # Placeholder - integrate with your AI logic
    # Could use Claude API, GPT, or template-based generation

    return """Dear [Recipient],

Thank you for your email. I've reviewed your message and wanted to respond promptly.

[Your response here]

Best regards,
[Your Name]"""


def generate_social_draft(task_content):
    """Generate AI-powered social media draft"""
    # Placeholder - integrate with your AI logic

    return """🚀 Exciting update!

[Your social media content here]

#AI #Automation #Productivity"""


def process_email_task(task_file):
    """
    Process email task:
    1. Claim by moving to In_Progress/cloud
    2. Generate draft reply
    3. Write to Pending_Approval/email
    4. Archive original to Done
    """
    claimed_path = claim_task(task_file, IN_PROGRESS_CLOUD)
    if not claimed_path:
        return

    try:
        # Read task
        with open(claimed_path, 'r', encoding='utf-8') as f:
            task_content = f.read()

        # Generate draft
        draft_reply = generate_email_draft(task_content)

        # Create approval file
        approval_file = PENDING_APPROVAL_EMAIL / f"APPROVAL_{task_file.name}"
        with open(approval_file, 'w', encoding='utf-8') as f:
            f.write(f"""---
status: pending
created: {datetime.now().isoformat()}
task_type: email_reply
cloud_processed: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
---

# Email Reply Approval

## Original Task
{task_content}

## Draft Reply
{draft_reply}

## Actions
- [ ] Approve: Change `status: pending` to `status: approved`
- [ ] Reject: Change `status: pending` to `status: rejected`
- [ ] Edit: Modify the draft reply above

## Instructions
1. Review the draft reply carefully
2. Edit the draft if needed
3. Change status to 'approved' or 'rejected'
4. Save this file
5. Local executor will handle the rest

---
*Generated by Cloud Processor at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
""")

        print(f"✅ Draft created: {approval_file.name}")

        # Archive original
        done_path = DONE / "email" / task_file.name
        done_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(claimed_path), str(done_path))
        print(f"✅ Archived: {task_file.name}")

    except Exception as e:
        print(f"❌ Error processing {task_file.name}: {e}")
        # Move to Failed
        failed_path = FAILED_CLOUD / task_file.name
        if claimed_path.exists():
            shutil.move(str(claimed_path), str(failed_path))
        print(f"❌ Moved to Failed: {task_file.name}")


def process_social_task(task_file):
    """
    Process social media task:
    1. Claim by moving to In_Progress/cloud
    2. Generate draft post
    3. Write to Pending_Approval/social
    4. Archive original to Done
    """
    claimed_path = claim_task(task_file, IN_PROGRESS_CLOUD)
    if not claimed_path:
        return

    try:
        # Read task
        with open(claimed_path, 'r', encoding='utf-8') as f:
            task_content = f.read()

        # Generate draft
        draft_post = generate_social_draft(task_content)

        # Create approval file
        approval_file = PENDING_APPROVAL_SOCIAL / f"APPROVAL_{task_file.name}"
        with open(approval_file, 'w', encoding='utf-8') as f:
            f.write(f"""---
status: pending
created: {datetime.now().isoformat()}
task_type: social_post
cloud_processed: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
platforms: [linkedin, twitter, facebook]
---

# Social Media Post Approval

## Original Task
{task_content}

## Draft Post
{draft_post}

## Platforms
- [ ] LinkedIn
- [ ] Twitter
- [ ] Facebook
- [ ] Instagram

## Actions
- [ ] Approve: Change `status: pending` to `status: approved`
- [ ] Reject: Change `status: pending` to `status: rejected`
- [ ] Edit: Modify the draft post above

## Instructions
1. Review the draft post
2. Select target platforms
3. Edit the draft if needed
4. Change status to 'approved' or 'rejected'
5. Save this file
6. Local executor will post to selected platforms

---
*Generated by Cloud Processor at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
""")

        print(f"✅ Draft created: {approval_file.name}")

        # Archive original
        done_path = DONE / "social" / task_file.name
        done_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(claimed_path), str(done_path))
        print(f"✅ Archived: {task_file.name}")

    except Exception as e:
        print(f"❌ Error processing {task_file.name}: {e}")
        # Move to Failed
        failed_path = FAILED_CLOUD / task_file.name
        if claimed_path.exists():
            shutil.move(str(claimed_path), str(failed_path))
        print(f"❌ Moved to Failed: {task_file.name}")


def main():
    """Main cloud processing loop"""
    print("🌥️  Cloud Processor Started")
    print(f"Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("")

    # Process email tasks
    email_tasks = list(NEEDS_ACTION_EMAIL.glob("*.md"))
    if email_tasks:
        print(f"📧 Processing {len(email_tasks)} email task(s)...")
        for task_file in email_tasks:
            process_email_task(task_file)
    else:
        print("📧 No email tasks to process")

    print("")

    # Process social tasks
    social_tasks = list(NEEDS_ACTION_SOCIAL.glob("*.md"))
    if social_tasks:
        print(f"📱 Processing {len(social_tasks)} social task(s)...")
        for task_file in social_tasks:
            process_social_task(task_file)
    else:
        print("📱 No social tasks to process")

    print("")
    print("✅ Cloud processing complete")


if __name__ == "__main__":
    main()
