"""
Gmail Watcher - Monitor Gmail Inbox for New Emails
===================================================
Automatically downloads new emails and creates task files in Needs_Action folder.
"""

import os
import sys
import time
import imaplib
import email
import json
from email.header import decode_header
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Configuration
VAULT_PATH = Path(__file__).parent.parent / "AI_Employee_Vault"
NEEDS_ACTION = VAULT_PATH / "Needs_Action"
LOGS_PATH = VAULT_PATH / "Logs"
PROCESSED_FILE = LOGS_PATH / "processed_emails.json"

# Gmail IMAP settings
IMAP_SERVER = "imap.gmail.com"
IMAP_PORT = 993

# Ensure directories exist
NEEDS_ACTION.mkdir(parents=True, exist_ok=True)
LOGS_PATH.mkdir(parents=True, exist_ok=True)


def load_processed_emails():
    """Load list of already processed email IDs"""
    if PROCESSED_FILE.exists():
        try:
            return json.loads(PROCESSED_FILE.read_text())
        except:
            return []
    return []


def save_processed_emails(processed_list):
    """Save list of processed email IDs"""
    PROCESSED_FILE.write_text(json.dumps(processed_list, indent=2))


def decode_mime_words(s):
    """Decode MIME encoded strings"""
    if s is None:
        return ""
    decoded_fragments = decode_header(s)
    return ''.join(
        str(fragment, encoding or 'utf-8') if isinstance(fragment, bytes) else str(fragment)
        for fragment, encoding in decoded_fragments
    )


def extract_email_body(msg):
    """Extract email body from message"""
    body = ""

    if msg.is_multipart():
        for part in msg.walk():
            content_type = part.get_content_type()
            content_disposition = str(part.get("Content-Disposition"))

            # Get text/plain parts
            if content_type == "text/plain" and "attachment" not in content_disposition:
                try:
                    body = part.get_payload(decode=True).decode()
                    break
                except:
                    pass
    else:
        try:
            body = msg.get_payload(decode=True).decode()
        except:
            body = str(msg.get_payload())

    return body.strip()


def create_task_file(email_data):
    """Create task file in Needs_Action folder"""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    # Clean sender name - remove invalid Windows filename characters
    sender_clean = email_data['from']
    # Remove angle brackets and extract just the email or name
    if '<' in sender_clean:
        # Extract email from "Name <email@domain.com>" format
        sender_clean = sender_clean.split('<')[0].strip()

    # Replace invalid characters: < > : " / \ | ? * and spaces
    invalid_chars = ['<', '>', ':', '"', '/', '\\', '|', '?', '*', ' ']
    for char in invalid_chars:
        sender_clean = sender_clean.replace(char, '_')

    # Replace @ and . for readability
    sender_clean = sender_clean.replace('@', '_at_').replace('.', '_')

    # Limit length and remove trailing underscores
    sender_clean = sender_clean[:30].strip('_')

    filename = f"email_{sender_clean}_{timestamp}.md"
    filepath = NEEDS_ACTION / filename

    content = f"""# Email from {email_data['from']}

**Type:** email_reply
**Priority:** Medium
**Received:** {email_data['date']}

## Original Email

**From:** {email_data['from']}
**Subject:** {email_data['subject']}
**Date:** {email_data['date']}

**Message:**
{email_data['body']}

---

## Task

Reply to this email.

**Context:** This is an incoming email that needs a response.

---

*Auto-generated by Gmail Watcher*
"""

    filepath.write_text(content, encoding='utf-8')
    print(f"[INFO] Created task file: {filename}")
    return filename


def check_gmail():
    """Check Gmail inbox for new emails"""
    email_address = os.getenv('EMAIL_ADDRESS')
    email_password = os.getenv('EMAIL_PASSWORD')

    if not email_address or not email_password:
        print("[ERROR] Missing EMAIL_ADDRESS or EMAIL_PASSWORD in .env file")
        return []

    try:
        # Connect to Gmail
        print(f"[INFO] Connecting to {IMAP_SERVER}...")
        mail = imaplib.IMAP4_SSL(IMAP_SERVER, IMAP_PORT)

        # Login
        print(f"[INFO] Logging in as {email_address}...")
        mail.login(email_address, email_password)

        # Select inbox
        mail.select("INBOX")

        # Search for unread emails
        print("[INFO] Searching for unread emails...")
        status, messages = mail.search(None, "UNSEEN")

        if status != "OK":
            print("[ERROR] Failed to search emails")
            return []

        email_ids = messages[0].split()

        if not email_ids:
            print("[INFO] No new emails found")
            return []

        print(f"[INFO] Found {len(email_ids)} new email(s)")

        # Load processed emails
        processed = load_processed_emails()
        new_emails = []

        # Process each email
        for email_id in email_ids:
            email_id_str = email_id.decode()

            # Skip if already processed
            if email_id_str in processed:
                continue

            # Fetch email
            status, msg_data = mail.fetch(email_id, "(RFC822)")

            if status != "OK":
                continue

            # Parse email
            for response_part in msg_data:
                if isinstance(response_part, tuple):
                    msg = email.message_from_bytes(response_part[1])

                    # Extract email data
                    subject = decode_mime_words(msg["Subject"])
                    from_addr = decode_mime_words(msg["From"])
                    date = msg["Date"]
                    body = extract_email_body(msg)

                    email_data = {
                        'id': email_id_str,
                        'from': from_addr,
                        'subject': subject,
                        'date': date,
                        'body': body
                    }

                    print(f"[INFO] Processing email from: {from_addr}")
                    print(f"[INFO] Subject: {subject}")

                    # Create task file
                    task_file = create_task_file(email_data)

                    # Mark as processed
                    processed.append(email_id_str)
                    new_emails.append(email_data)

        # Save processed list
        save_processed_emails(processed)

        # Logout
        mail.logout()

        return new_emails

    except imaplib.IMAP4.error as e:
        print(f"[ERROR] IMAP error: {e}")
        print("[TIP] Make sure you're using a Gmail App Password")
        print("[TIP] Enable IMAP in Gmail settings")
        return []
    except Exception as e:
        print(f"[ERROR] Failed to check Gmail: {e}")
        return []


def watch_continuous(check_interval=60):
    """Watch Gmail continuously"""
    print(f"[INFO] Gmail Watcher started")
    print(f"[INFO] Checking every {check_interval} seconds")
    print(f"[INFO] Press Ctrl+C to stop")

    try:
        while True:
            print(f"\n[INFO] Checking Gmail at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
            new_emails = check_gmail()

            if new_emails:
                print(f"[SUCCESS] Processed {len(new_emails)} new email(s)")

            print(f"[INFO] Next check in {check_interval} seconds...")
            time.sleep(check_interval)

    except KeyboardInterrupt:
        print("\n[INFO] Gmail Watcher stopped by user")


def main():
    import argparse

    parser = argparse.ArgumentParser(description='Gmail Watcher - Monitor inbox for new emails')
    parser.add_argument('--once', action='store_true', help='Check once and exit')
    parser.add_argument('--interval', type=int, default=60, help='Check interval in seconds (default: 60)')

    args = parser.parse_args()

    if args.once:
        print("[INFO] Running single check...")
        new_emails = check_gmail()
        if new_emails:
            print(f"[SUCCESS] Processed {len(new_emails)} new email(s)")
        else:
            print("[INFO] No new emails")
    else:
        watch_continuous(args.interval)


if __name__ == "__main__":
    main()
