"""
LinkedIn Watcher - Monitor LinkedIn for Messages and Notifications
===================================================================
Monitors LinkedIn for new messages, connection requests, and notifications.
Creates task files for items requiring action.
"""

import os
import sys
import time
import json
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Configuration
VAULT_PATH = Path(__file__).parent.parent / "AI_Employee_Vault"
NEEDS_ACTION = VAULT_PATH / "Needs_Action"
LOGS_PATH = VAULT_PATH / "Logs"
PROCESSED_FILE = LOGS_PATH / "processed_linkedin.json"
SESSION_FILE = LOGS_PATH / "sessions" / "linkedin_session.json"

# Ensure directories exist
NEEDS_ACTION.mkdir(parents=True, exist_ok=True)
LOGS_PATH.mkdir(parents=True, exist_ok=True)
SESSION_FILE.parent.mkdir(parents=True, exist_ok=True)


def load_processed_items():
    """Load list of already processed item IDs"""
    if PROCESSED_FILE.exists():
        try:
            return json.loads(PROCESSED_FILE.read_text())
        except:
            return []
    return []


def save_processed_items(processed_list):
    """Save list of processed item IDs"""
    PROCESSED_FILE.write_text(json.dumps(processed_list, indent=2))


def create_task_file(item_data):
    """Create task file in Needs_Action folder"""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    sender_clean = item_data['sender'].replace(' ', '_').replace('/', '_')[:30]
    filename = f"linkedin_{item_data['type']}_{sender_clean}_{timestamp}.md"
    filepath = NEEDS_ACTION / filename

    content = f"""# LinkedIn {item_data['type'].title()} from {item_data['sender']}

**Type:** linkedin_{item_data['type']}
**Priority:** {item_data['priority']}
**Received:** {item_data['time']}

## Details

**From:** {item_data['sender']}
**Time:** {item_data['time']}

**Message:**
{item_data['message']}

---

## Task

Respond to this LinkedIn {item_data['type']}.

**Context:** This is an incoming LinkedIn {item_data['type']} that needs attention.

---

*Auto-generated by LinkedIn Watcher*
"""

    filepath.write_text(content, encoding='utf-8')
    print(f"[INFO] Created task file: {filename}")
    return filename


def check_linkedin_once():
    """Check LinkedIn for new messages/notifications using persistent profile (auto-login!)"""
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        print("[ERROR] Playwright not installed")
        print("[TIP] Run: pip install playwright")
        print("[TIP] Then run: playwright install chromium")
        return []

    # Use persistent browser profile
    profile_path = VAULT_PATH / "Browser_Profiles" / "linkedin_profile"
    profile_path.mkdir(parents=True, exist_ok=True)

    print("[INFO] Starting LinkedIn monitor...")

    with sync_playwright() as p:
        # Launch with persistent profile (auto-login!)
        print("[INFO] Loading LinkedIn profile...")
        context = p.chromium.launch_persistent_context(
            user_data_dir=str(profile_path),
            headless=False,
            args=['--start-maximized', '--disable-blink-features=AutomationControlled'],
            user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            viewport={'width': 1366, 'height': 768}
        )

        page = context.pages[0] if context.pages else context.new_page()

        print("[INFO] Opening LinkedIn...")
        page.goto("https://www.linkedin.com", wait_until="domcontentloaded", timeout=60000)
        page.wait_for_timeout(8000)

        # Check if login required
        if "login" in page.url.lower() or "authwall" in page.url.lower():
            print("\n" + "=" * 60)
            print("LOGIN REQUIRED - FIRST TIME ONLY")
            print("=" * 60)
            print("\nPlease login manually in the browser window.")
            print("Your login will be saved permanently in the browser profile.")
            print("You won't need to login again!")
            print("\nWaiting 3 minutes for manual login...")
            print("=" * 60)

            try:
                # Wait for successful login (feed page loads)
                page.wait_for_url("**/feed/**", timeout=180000)
                print("\n[SUCCESS] Login saved! Next time you'll be auto-logged in.")

                page.wait_for_timeout(3000)

            except:
                print("[ERROR] Login timeout - please try again")
                context.close()
                return []
        else:
            print("[SUCCESS] Already logged in! (using saved profile)")

        print("[INFO] LinkedIn loaded successfully")

        processed = load_processed_items()
        new_items = []

        # Check messages
        print("[INFO] Navigating to messages...")
        page.goto("https://www.linkedin.com/messaging/", wait_until="domcontentloaded", timeout=60000)
        page.wait_for_timeout(8000)

        # Check if we're actually logged in by looking for messaging elements
        print("[INFO] Verifying login status...")
        page.wait_for_timeout(3000)

        # Check if login is required on messaging page
        if "login" in page.url.lower() or "authwall" in page.url.lower():
            print("\n" + "=" * 60)
            print("LOGIN REQUIRED ON MESSAGING PAGE")
            print("=" * 60)
            print("\nPlease login manually in the browser window.")
            print("Browser will stay open for 3 minutes...")
            print("=" * 60 + "\n")

            page.wait_for_timeout(180000)

            # Save session after login
            try:
                context.storage_state(path=str(SESSION_FILE))
                print("[INFO] Session saved")
            except:
                pass

        print("[INFO] Messages page loaded")
        print("\n" + "=" * 60)
        print("BROWSER WILL STAY OPEN FOR 2 MINUTES")
        print("=" * 60)
        print("\nYou can:")
        print("- Check your messages manually")
        print("- Verify login is working")
        print("- Close browser manually anytime (Ctrl+W)")
        print("\nAuto-closing in 2 minutes...")
        print("=" * 60 + "\n")

        page.wait_for_timeout(120000)

        # Save processed and close
        save_processed_items(processed)
        print("[INFO] Closing browser...")
        context.close()
        return new_items


def main():
    import argparse
    parser = argparse.ArgumentParser(description='LinkedIn Watcher')
    parser.add_argument('--once', action='store_true', help='Check once and exit')
    parser.add_argument('--continuous', action='store_true', help='Run continuously')
    parser.add_argument('--interval', type=int, default=300, help='Check interval in seconds (default: 300)')
    args = parser.parse_args()

    if args.continuous:
        print(f"[INFO] Running continuously (every {args.interval} seconds)")
        print("[INFO] Press Ctrl+C to stop")

        try:
            while True:
                print(f"\n[INFO] Running at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
                new_items = check_linkedin_once()

                if new_items:
                    print(f"[SUCCESS] Found {len(new_items)} new item(s)")
                else:
                    print("[INFO] No new items")

                print(f"[INFO] Next check in {args.interval} seconds...")
                time.sleep(args.interval)

        except KeyboardInterrupt:
            print("\n[INFO] LinkedIn Watcher stopped by user")
    else:
        # Default behavior: run once (whether --once is specified or not)
        print("[INFO] Running single check...")
        check_linkedin_once()


if __name__ == "__main__":
    main()
