"""
LinkedIn Watcher - Monitor LinkedIn for Messages and Notifications
===================================================================
Monitors LinkedIn for new messages, connection requests, and notifications.
Creates task files for items requiring action.
"""

import os
import sys
import time
import json
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Configuration
VAULT_PATH = Path(__file__).parent.parent / "AI_Employee_Vault"
NEEDS_ACTION = VAULT_PATH / "Needs_Action"
LOGS_PATH = VAULT_PATH / "Logs"
PROCESSED_FILE = LOGS_PATH / "processed_linkedin.json"
SESSION_FILE = LOGS_PATH / "sessions" / "linkedin_session.json"

# Ensure directories exist
NEEDS_ACTION.mkdir(parents=True, exist_ok=True)
LOGS_PATH.mkdir(parents=True, exist_ok=True)
SESSION_FILE.parent.mkdir(parents=True, exist_ok=True)


def load_processed_items():
    """Load list of already processed item IDs"""
    if PROCESSED_FILE.exists():
        try:
            return json.loads(PROCESSED_FILE.read_text())
        except:
            return []
    return []


def save_processed_items(processed_list):
    """Save list of processed item IDs"""
    PROCESSED_FILE.write_text(json.dumps(processed_list, indent=2))


def create_task_file(item_data):
    """Create task file in Needs_Action folder"""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    sender_clean = item_data['sender'].replace(' ', '_').replace('/', '_')[:30]
    filename = f"linkedin_{item_data['type']}_{sender_clean}_{timestamp}.md"
    filepath = NEEDS_ACTION / filename

    content = f"""# LinkedIn {item_data['type'].title()} from {item_data['sender']}

**Type:** linkedin_{item_data['type']}
**Priority:** {item_data['priority']}
**Received:** {item_data['time']}

## Details

**From:** {item_data['sender']}
**Time:** {item_data['time']}

**Message:**
{item_data['message']}

---

## Task

Respond to this LinkedIn {item_data['type']}.

**Context:** This is an incoming LinkedIn {item_data['type']} that needs attention.

---

*Auto-generated by LinkedIn Watcher*
"""

    filepath.write_text(content, encoding='utf-8')
    print(f"[INFO] Created task file: {filename}")
    return filename


def check_linkedin_once():
    """Check LinkedIn for new messages/notifications (single check)"""
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        print("[ERROR] Playwright not installed")
        print("[TIP] Run: pip install playwright")
        print("[TIP] Then run: playwright install chromium")
        return []

    print("[INFO] Starting LinkedIn monitor...")

    with sync_playwright() as p:
        browser = p.chromium.launch(
            headless=False,
            args=['--start-maximized', '--disable-blink-features=AutomationControlled']
        )

        # Load session if exists
        if SESSION_FILE.exists():
            try:
                print("[INFO] Loading saved session")
                context = browser.new_context(
                    storage_state=str(SESSION_FILE),
                    user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
                    no_viewport=True
                )
            except:
                print("[INFO] Creating new context")
                context = browser.new_context(
                    user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
                    no_viewport=True
                )
        else:
            context = browser.new_context(
                user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
                no_viewport=True
            )

        page = context.new_page()
        page.goto("https://www.linkedin.com")
        page.wait_for_timeout(5000)

        # Check if login required
        if "login" in page.url or "authwall" in page.url:
            print("[INFO] Login required")
            page.wait_for_selector('div[role="main"]', timeout=120000)
            context.storage_state(path=str(SESSION_FILE))
            print("[SUCCESS] Session saved")

        processed = load_processed_items()
        new_items = []

        # Check messages
        print("[INFO] Checking messages...")
        page.goto("https://www.linkedin.com/messaging/")
        page.wait_for_timeout(3000)

        # Save processed and close
        save_processed_items(processed)
        browser.close()
        return new_items


def main():
    import argparse
    parser = argparse.ArgumentParser(description='LinkedIn Watcher')
    parser.add_argument('--once', action='store_true', help='Check once')
    parser.add_argument('--interval', type=int, default=300, help='Interval in seconds')
    args = parser.parse_args()

    if args.once:
        check_linkedin_once()
    else:
        print("[INFO] Continuous mode not yet implemented")
        print("[TIP] Use --once for now")


if __name__ == "__main__":
    main()
