"""
Smart Hackathon Orchestrator - Content Generation
==================================================
Generates social media content for LinkedIn, Twitter, and WhatsApp.
Saves to Pending_Approval/ for human review.

SAFETY: No auto-posting. Human approval required.
"""

import os
import sys
import json
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

# Configuration
VAULT_PATH = Path(__file__).parent.parent / "AI_Employee_Vault"
PENDING_APPROVAL = VAULT_PATH / "Pending_Approval"
LOGS_PATH = VAULT_PATH / "Logs"

# Ensure directories exist
PENDING_APPROVAL.mkdir(parents=True, exist_ok=True)
LOGS_PATH.mkdir(parents=True, exist_ok=True)


def log_action(action, platform, filename, result):
    """Log all actions to orchestrator.log"""
    log_file = LOGS_PATH / "orchestrator.log"

    log_entry = {
        "timestamp": datetime.now().isoformat(),
        "action": action,
        "platform": platform,
        "filename": filename,
        "result": result
    }

    with open(log_file, 'a', encoding='utf-8') as f:
        f.write(json.dumps(log_entry) + '\n')


def generate_linkedin_post(topic):
    """Generate LinkedIn post content"""
    content = f"""🚀 {topic}

As we navigate the evolving landscape of technology, it's crucial to stay informed and adapt to emerging trends.

Key insights:
• Innovation drives progress
• Collaboration amplifies impact
• Continuous learning is essential

What are your thoughts on this topic? Let's discuss in the comments!

#Technology #Innovation #ProfessionalDevelopment #AI #FutureOfWork"""

    return {
        "platform": "LinkedIn",
        "content": content,
        "hashtags": ["Technology", "Innovation", "ProfessionalDevelopment", "AI", "FutureOfWork"],
        "character_count": len(content)
    }


def generate_twitter_post(topic):
    """Generate Twitter/X post content"""
    content = f"""🔥 {topic}

The future is being built today. Stay curious, stay innovative.

#Tech #Innovation #AI #FutureOfWork"""

    return {
        "platform": "Twitter",
        "content": content,
        "hashtags": ["Tech", "Innovation", "AI", "FutureOfWork"],
        "character_count": len(content)
    }


def generate_whatsapp_message(topic):
    """Generate WhatsApp message content"""
    content = f"""Hi! 👋

I wanted to share something interesting about {topic}.

This is a rapidly evolving area with significant implications for the future. Would love to hear your thoughts on this!

Let me know if you'd like to discuss further."""

    return {
        "platform": "WhatsApp",
        "content": content,
        "hashtags": [],
        "character_count": len(content)
    }


def save_to_pending(platform, content_data, topic):
    """Save generated content to Pending_Approval folder"""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    topic_clean = topic.replace(' ', '_').replace('/', '_')[:30]
    filename = f"{platform.lower()}_{topic_clean}_{timestamp}.md"
    filepath = PENDING_APPROVAL / filename

    markdown_content = f"""---
platform: {platform}
topic: {topic}
created: {datetime.now().isoformat()}
status: Pending
character_count: {content_data['character_count']}
---

# {platform} Post - {topic}

## Generated Content

{content_data['content']}

---

## Hashtags

{', '.join(['#' + tag for tag in content_data['hashtags']])}

---

## Metadata

- **Platform:** {platform}
- **Topic:** {topic}
- **Created:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
- **Status:** Pending
- **Character Count:** {content_data['character_count']}

---

## Approval Instructions

To approve this post:
```bash
python scripts/approval_manager.py approve {filename}
```

To reject this post:
```bash
python scripts/approval_manager.py reject {filename}
```

---

*Generated by Smart Hackathon Orchestrator*
*SAFETY: Human approval required before posting*
"""

    filepath.write_text(markdown_content, encoding='utf-8')
    print(f"[CREATED] {filename}")

    log_action("generate", platform, filename, "success")

    return filename


def run_orchestrator(topic):
    """Main orchestrator function"""
    print("=" * 60)
    print("Smart Hackathon Orchestrator")
    print("=" * 60)
    print(f"\nTopic: {topic}\n")

    generated_files = []

    # Generate LinkedIn post
    print("[1/3] Generating LinkedIn post...")
    linkedin_data = generate_linkedin_post(topic)
    linkedin_file = save_to_pending("LinkedIn", linkedin_data, topic)
    generated_files.append(linkedin_file)

    # Generate Twitter post
    print("[2/3] Generating Twitter post...")
    twitter_data = generate_twitter_post(topic)
    twitter_file = save_to_pending("Twitter", twitter_data, topic)
    generated_files.append(twitter_file)

    # Generate WhatsApp message
    print("[3/3] Generating WhatsApp message...")
    whatsapp_data = generate_whatsapp_message(topic)
    whatsapp_file = save_to_pending("WhatsApp", whatsapp_data, topic)
    generated_files.append(whatsapp_file)

    print("\n" + "=" * 60)
    print("Content Generation Complete!")
    print("=" * 60)
    print(f"\nGenerated {len(generated_files)} posts:")
    for f in generated_files:
        print(f"  - {f}")

    print(f"\nLocation: {PENDING_APPROVAL}")
    print("\nNext Steps:")
    print("1. Review generated content in Pending_Approval/")
    print("2. Run: python scripts/approval_manager.py")
    print("3. Approve or reject each post")
    print("4. Run: python scripts/post_with_playwright.py <platform> <filename>")
    print("\n" + "=" * 60)

    return generated_files


def main():
    import argparse

    parser = argparse.ArgumentParser(
        description='Smart Hackathon Orchestrator - Generate social media content',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python scripts/run_smart_orchestrator.py "AI in Healthcare Trends"
  python scripts/run_smart_orchestrator.py "Future of Remote Work"
  python scripts/run_smart_orchestrator.py "Sustainable Technology"

Safety:
  - No auto-posting
  - Human approval required
  - Session-based authentication only
  - Supervised automation
        """
    )

    parser.add_argument('topic', type=str, help='Topic for content generation')

    args = parser.parse_args()

    try:
        run_orchestrator(args.topic)
    except Exception as e:
        print(f"\n[ERROR] Orchestrator failed: {e}")
        log_action("orchestrator", "all", "N/A", f"error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
