"""
WhatsApp Watcher - Monitor WhatsApp Web for New Messages
=========================================================
Uses Playwright to monitor WhatsApp Web and create task files for new messages.
"""

import os
import sys
import time
import json
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Configuration
VAULT_PATH = Path(__file__).parent.parent / "AI_Employee_Vault"
NEEDS_ACTION = VAULT_PATH / "Needs_Action"
LOGS_PATH = VAULT_PATH / "Logs"
PROCESSED_FILE = LOGS_PATH / "processed_whatsapp.json"
SESSION_FILE = LOGS_PATH / "whatsapp_session.json"

# Ensure directories exist
NEEDS_ACTION.mkdir(parents=True, exist_ok=True)
LOGS_PATH.mkdir(parents=True, exist_ok=True)


def load_processed_messages():
    """Load list of already processed message IDs"""
    if PROCESSED_FILE.exists():
        try:
            return json.loads(PROCESSED_FILE.read_text())
        except:
            return []
    return []


def save_processed_messages(processed_list):
    """Save list of processed message IDs"""
    PROCESSED_FILE.write_text(json.dumps(processed_list, indent=2))


def create_task_file(message_data):
    """Create task file in Needs_Action folder"""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    sender_clean = message_data['sender'].replace(' ', '_').replace('/', '_')[:30]
    filename = f"whatsapp_{sender_clean}_{timestamp}.md"
    filepath = NEEDS_ACTION / filename

    content = f"""# WhatsApp from {message_data['sender']}

**Type:** whatsapp_reply
**Priority:** High
**Received:** {message_data['time']}

## Original Message

**From:** {message_data['sender']}
**Time:** {message_data['time']}

**Message:**
{message_data['message']}

---

## Task

Reply to this WhatsApp message.

**Context:** This is an incoming WhatsApp message that needs a response.

---

*Auto-generated by WhatsApp Watcher*
"""

    filepath.write_text(content, encoding='utf-8')
    print(f"[INFO] Created task file: {filename}")
    return filename


def check_messages_once(page, processed):
    """Check for new messages once (browser already open)"""
    new_messages = []

    try:
        # Look for unread message indicators
        print("[INFO] Checking for unread messages...")

        # Wait a bit for page to be ready
        page.wait_for_timeout(5000)

        # Try multiple selectors for chat list items
        chat_selectors = [
            'div[role="listitem"]',
            'div[data-testid="cell-frame-container"]',
            'div._ak8l',  # Common WhatsApp class
            'div[class*="chat"]',
            'div[id="pane-side"] > div > div > div',  # Side pane chats
            '#pane-side [role="listitem"]',  # Chats in side pane
            'div[aria-label*="Chat list"] div[role="listitem"]',  # More specific
        ]

        all_chats = []
        for selector in chat_selectors:
            all_chats = page.locator(selector).all()
            if all_chats:
                print(f"[INFO] Found {len(all_chats)} chats using selector: {selector}")
                break

        if not all_chats:
            print("[INFO] No chats found with any selector")
            print("[DEBUG] Trying to find chat list container...")
            # Debug: check what's on the page
            try:
                # Check if side pane exists
                side_pane = page.locator('#pane-side')
                if side_pane.count() > 0:
                    print("[DEBUG] Side pane found, but no chats detected")
                    print("[DEBUG] This might be normal if you have no chats or all chats are read")
                else:
                    print("[DEBUG] Side pane not found - WhatsApp might not be fully loaded")

                page_text = page.locator('body').inner_text()
                if "WhatsApp" in page_text:
                    print("[DEBUG] WhatsApp page is loaded")
                else:
                    print("[DEBUG] Page may not be fully loaded")
            except Exception as e:
                print(f"[DEBUG] Error checking page: {e}")
            return []

        # Filter chats that have unread indicators
        unread_chats = []
        print(f"[INFO] Scanning {min(len(all_chats), 20)} chats for unread messages...")

        for i, chat in enumerate(all_chats[:20]):  # Check first 20 chats
            try:
                # Try multiple methods to detect unread messages
                has_unread = False

                # Method 1: Look for unread count badge
                if chat.locator('span[data-testid="icon-unread-count"]').count() > 0:
                    has_unread = True
                    print(f"[DEBUG] Chat {i+1}: Found unread via icon-unread-count")

                # Method 2: Look for aria-label with unread
                elif chat.locator('span[aria-label*="unread"]').count() > 0:
                    has_unread = True
                    print(f"[DEBUG] Chat {i+1}: Found unread via aria-label")

                # Method 3: Look for green badge/dot (common unread indicator)
                elif chat.locator('div[aria-label*="unread"]').count() > 0:
                    has_unread = True
                    print(f"[DEBUG] Chat {i+1}: Found unread via div aria-label")

                # Method 4: Look for badge with class containing 'unread' or 'badge'
                elif chat.locator('[class*="unread"]').count() > 0:
                    has_unread = True
                    print(f"[DEBUG] Chat {i+1}: Found unread via class")

                # Method 5: Look for any badge/count element
                elif chat.locator('span._aou8').count() > 0:  # WhatsApp badge class
                    has_unread = True
                    print(f"[DEBUG] Chat {i+1}: Found unread via badge class")

                if has_unread:
                    unread_chats.append(chat)
            except Exception as e:
                print(f"[DEBUG] Error checking chat {i+1}: {e}")
                continue

        if not unread_chats:
            print("[INFO] No unread messages found")
            return []

        print(f"[SUCCESS] Found {len(unread_chats)} unread chat(s)!")

        # Process each unread chat
        for i, chat_item in enumerate(unread_chats[:5]):  # Limit to 5
            try:
                # Get sender name
                sender = "Unknown"
                try:
                    title_elem = chat_item.locator('span[title]').first
                    if title_elem.count() > 0:
                        sender = title_elem.get_attribute('title')

                    if sender == "Unknown":
                        name_elem = chat_item.locator('span[dir="auto"]').first
                        if name_elem.count() > 0:
                            sender = name_elem.inner_text()
                except Exception as e:
                    print(f"[WARNING] Could not extract sender name: {e}")

                print(f"[INFO] Chat from: {sender}")

                # Click on the chat
                chat_item.click()
                page.wait_for_timeout(3000)

                # Get the last incoming message - try multiple selectors
                message_selectors = [
                    'div.message-in span.selectable-text',
                    'div[data-pre-plain-text] span.selectable-text',
                    'span.selectable-text',  # Broader selector
                    'span[dir="ltr"]',
                    'div[class*="message"] span',
                    'div._akbu span',  # WhatsApp message class
                    'div[role="row"] span[dir="ltr"]',
                ]

                message_text = None
                for selector in message_selectors:
                    try:
                        messages = page.locator(selector).all()
                        if messages and len(messages) > 0:
                            # Get last message
                            last_msg = messages[-1]
                            text = last_msg.inner_text().strip()
                            if text and len(text) > 0:
                                message_text = text
                                print(f"[DEBUG] Extracted message using: {selector}")
                                break
                    except Exception as e:
                        continue

                if not message_text:
                    print(f"[WARNING] Could not extract message text")
                    print(f"[DEBUG] Trying to get any text from message area...")
                    try:
                        # Last resort: get all text from main chat area
                        main_area = page.locator('div[data-testid="conversation-panel-body"]')
                        if main_area.count() > 0:
                            all_text = main_area.inner_text()
                            lines = [l.strip() for l in all_text.split('\n') if l.strip()]
                            if lines:
                                message_text = lines[-1]  # Get last line
                                print(f"[DEBUG] Got text from conversation panel: {message_text[:50]}...")
                    except:
                        pass

                if not message_text:
                    print(f"[WARNING] Still could not extract message, skipping")
                    continue

                print(f"[INFO] Message: {message_text[:50]}...")

                # Create unique message ID
                message_id = f"{sender}_{message_text[:30]}_{datetime.now().strftime('%Y%m%d')}"

                # Skip if already processed
                if message_id in processed:
                    print(f"[INFO] Already processed, skipping")
                    continue

                message_data = {
                    'sender': sender,
                    'message': message_text,
                    'time': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
                }

                print(f"[SUCCESS] New message from: {sender}")

                # Create task file
                create_task_file(message_data)

                # Mark as processed
                processed.append(message_id)
                new_messages.append(message_data)

            except Exception as e:
                print(f"[WARNING] Failed to process chat: {e}")
                continue

        # Save processed list
        save_processed_messages(processed)

    except Exception as e:
        print(f"[ERROR] Failed to check messages: {e}")

    return new_messages


def check_whatsapp():
    """Check WhatsApp Web for new messages using persistent profile (auto-login!)"""
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        print("[ERROR] Playwright not installed")
        print("[TIP] Run: pip install playwright")
        print("[TIP] Then run: playwright install chromium")
        return []

    # Use persistent browser profile
    profile_path = VAULT_PATH / "Browser_Profiles" / "whatsapp_profile"
    profile_path.mkdir(parents=True, exist_ok=True)

    print("[INFO] Starting WhatsApp Web monitor...")

    with sync_playwright() as p:
        # Launch with persistent profile (auto-login!)
        print("[INFO] Loading WhatsApp profile...")
        context = p.chromium.launch_persistent_context(
            user_data_dir=str(profile_path),
            headless=False,
            args=['--start-maximized', '--disable-blink-features=AutomationControlled'],
            user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            viewport={'width': 1366, 'height': 768}
        )

        page = context.pages[0] if context.pages else context.new_page()

        # Navigate to WhatsApp Web
        print("[INFO] Opening WhatsApp Web...")
        page.goto("https://web.whatsapp.com")

        # Wait for login
        try:
            print("[INFO] Waiting for page to load...")
            page.wait_for_timeout(10000)

            # Check if QR code is present
            if page.locator('canvas[aria-label="Scan this QR code to link a device!"]').count() > 0:
                print("[INFO] QR Code detected - Please scan with your phone")
                print("[INFO] Waiting for login (up to 3 minutes)...")
                page.wait_for_selector('div[aria-label="Chat list"]', timeout=180000)
                print("[SUCCESS] Login successful!")

                # Save complete browser state (cookies, localStorage, sessionStorage, IndexedDB)
                context.storage_state(path=str(SESSION_FILE))
                print("[INFO] Session saved (complete browser state)")

            print("[INFO] Waiting for chats to load...")
            page.wait_for_timeout(5000)

        except Exception as e:
            print(f"[ERROR] Failed to login: {e}")
            browser.close()
            return []

        # Load processed messages and check
        processed = load_processed_messages()
        new_messages = check_messages_once(page, processed)

        # Close browser
        browser.close()

        return new_messages


def watch_continuous(check_interval=300):
    """Watch WhatsApp continuously with browser staying open"""
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        print("[ERROR] Playwright not installed")
        print("[TIP] Run: pip install playwright")
        print("[TIP] Then run: playwright install chromium")
        return

    print(f"[INFO] WhatsApp Watcher started")
    print(f"[INFO] Checking every {check_interval} seconds")
    print(f"[INFO] Press Ctrl+C to stop")

    with sync_playwright() as p:
        # Launch browser once
        print("[INFO] Launching browser...")
        browser = p.chromium.launch(
            headless=False,
            args=['--start-maximized', '--disable-blink-features=AutomationControlled']
        )

        # Load complete browser state if exists
        if SESSION_FILE.exists():
            try:
                print("[INFO] Loading saved session")
                context = browser.new_context(
                    storage_state=str(SESSION_FILE),
                    user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                    no_viewport=True
                )
            except:
                print("[INFO] No valid session found, creating new context")
                context = browser.new_context(
                    user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                    no_viewport=True
                )
        else:
            print("[INFO] No session file found, creating new context")
            context = browser.new_context(
                user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                no_viewport=True
            )

        page = context.new_page()

        # Navigate to WhatsApp Web
        print("[INFO] Opening WhatsApp Web...")
        try:
            page.goto("https://web.whatsapp.com", timeout=60000)
        except Exception as e:
            print(f"[ERROR] Failed to open WhatsApp Web: {e}")
            browser.close()
            return

        # Wait for login
        try:
            print("[INFO] Waiting for page to load...")
            page.wait_for_timeout(10000)

            # Check if QR code is present
            if page.locator('canvas[aria-label="Scan this QR code to link a device!"]').count() > 0:
                print("[INFO] QR Code detected - Please scan with your phone")
                print("[INFO] Waiting for login (up to 3 minutes)...")
                page.wait_for_selector('div[aria-label="Chat list"]', timeout=180000)
                print("[SUCCESS] Login successful!")

                # Save complete browser state (cookies, localStorage, sessionStorage, IndexedDB)
                context.storage_state(path=str(SESSION_FILE))
                print("[INFO] Session saved (complete browser state)")

            print("[INFO] Waiting for chats to load...")
            page.wait_for_timeout(5000)
            print("[SUCCESS] WhatsApp Web is ready!")

        except Exception as e:
            print(f"[ERROR] Failed to login: {e}")
            browser.close()
            return

        # Load processed messages
        processed = load_processed_messages()

        print("\n" + "="*60)
        print("WhatsApp Monitor Active - Browser will stay open")
        print("="*60)

        # Continuous monitoring loop
        try:
            while True:
                print(f"\n[{datetime.now().strftime('%H:%M:%S')}] Checking for new messages...")

                try:
                    new_messages = check_messages_once(page, processed)

                    if new_messages:
                        print(f"[SUCCESS] Processed {len(new_messages)} new message(s)")
                    else:
                        print("[INFO] No new messages")

                except Exception as e:
                    print(f"[ERROR] Error during check: {e}")
                    print("[INFO] Will retry on next check...")

                print(f"[INFO] Next check in {check_interval} seconds...")
                time.sleep(check_interval)

        except KeyboardInterrupt:
            print("\n\n[INFO] WhatsApp Watcher stopped by user")
        finally:
            print("[INFO] Closing browser...")
            browser.close()
            print("[INFO] Browser closed")


def main():
    import argparse

    parser = argparse.ArgumentParser(description='WhatsApp Watcher - Monitor for new messages')
    parser.add_argument('--once', action='store_true', help='Check once and exit')
    parser.add_argument('--interval', type=int, default=120, help='Check interval in seconds (default: 120)')

    args = parser.parse_args()

    if args.once:
        print("[INFO] Running single check...")
        new_messages = check_whatsapp()
        if new_messages:
            print(f"[SUCCESS] Processed {len(new_messages)} new message(s)")
        else:
            print("[INFO] No new messages")
    else:
        watch_continuous(args.interval)


if __name__ == "__main__":
    main()
