"""
WhatsApp Watcher - Monitor WhatsApp Web for New Messages
=========================================================
Uses Playwright to monitor WhatsApp Web and create task files for new messages.
"""

import os
import sys
import time
import json
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Configuration
VAULT_PATH = Path(__file__).parent.parent / "AI_Employee_Vault"
NEEDS_ACTION = VAULT_PATH / "Needs_Action"
LOGS_PATH = VAULT_PATH / "Logs"
PROCESSED_FILE = LOGS_PATH / "processed_whatsapp.json"
SESSION_FILE = LOGS_PATH / "whatsapp_session.json"

# Ensure directories exist
NEEDS_ACTION.mkdir(parents=True, exist_ok=True)
LOGS_PATH.mkdir(parents=True, exist_ok=True)


def load_processed_messages():
    """Load list of already processed message IDs"""
    if PROCESSED_FILE.exists():
        try:
            return json.loads(PROCESSED_FILE.read_text())
        except:
            return []
    return []


def save_processed_messages(processed_list):
    """Save list of processed message IDs"""
    PROCESSED_FILE.write_text(json.dumps(processed_list, indent=2))


def create_task_file(message_data):
    """Create task file in Needs_Action folder"""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    sender_clean = message_data['sender'].replace(' ', '_').replace('/', '_')[:30]
    filename = f"whatsapp_{sender_clean}_{timestamp}.md"
    filepath = NEEDS_ACTION / filename

    content = f"""# WhatsApp from {message_data['sender']}

**Type:** whatsapp_reply
**Priority:** High
**Received:** {message_data['time']}

## Original Message

**From:** {message_data['sender']}
**Time:** {message_data['time']}

**Message:**
{message_data['message']}

---

## Task

Reply to this WhatsApp message.

**Context:** This is an incoming WhatsApp message that needs a response.

---

*Auto-generated by WhatsApp Watcher*
"""

    filepath.write_text(content, encoding='utf-8')
    print(f"[INFO] Created task file: {filename}")
    return filename


def check_whatsapp():
    """Check WhatsApp Web for new messages using Playwright"""
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        print("[ERROR] Playwright not installed")
        print("[TIP] Run: pip install playwright")
        print("[TIP] Then run: playwright install chromium")
        return []

    print("[INFO] Starting WhatsApp Web monitor...")

    with sync_playwright() as p:
        # Launch browser
        browser = p.chromium.launch(headless=False)  # headless=False to see QR code
        context = browser.new_context()

        # Load session if exists
        if SESSION_FILE.exists():
            try:
                session_data = json.loads(SESSION_FILE.read_text())
                context.add_cookies(session_data.get('cookies', []))
                print("[INFO] Loaded saved session")
            except:
                print("[INFO] No valid session found, will need to scan QR code")

        page = context.new_page()

        # Navigate to WhatsApp Web
        print("[INFO] Opening WhatsApp Web...")
        page.goto("https://web.whatsapp.com")

        # Wait for either QR code or chat list
        try:
            # Wait longer for page to load
            print("[INFO] Waiting for page to load (15 seconds)...")
            page.wait_for_timeout(15000)

            # Take screenshot for debugging
            screenshot_path = LOGS_PATH / f"whatsapp_{datetime.now().strftime('%Y%m%d_%H%M%S')}.png"
            page.screenshot(path=str(screenshot_path))
            print(f"[DEBUG] Screenshot saved: {screenshot_path}")

            # Check if QR code is present
            if page.locator('canvas[aria-label="Scan this QR code to link a device!"]').count() > 0:
                print("[INFO] QR Code detected - Please scan with your phone")
                print("[INFO] Waiting for login...")
                # Wait for chats to appear (login successful)
                page.wait_for_selector('div[aria-label="Chat list"]', timeout=60000)
                print("[SUCCESS] Login successful!")

                # Save session
                cookies = context.cookies()
                session_data = {'cookies': cookies}
                SESSION_FILE.write_text(json.dumps(session_data, indent=2))
                print("[INFO] Session saved")

        except Exception as e:
            print(f"[ERROR] Failed to login: {e}")
            browser.close()
            return []

        # Load processed messages
        processed = load_processed_messages()
        new_messages = []

        try:
            # Get all chats (not just unread - WhatsApp selectors change frequently)
            print("[INFO] Checking for messages...")
            print("[INFO] Looking for chat list...")

            # Wait even more for chats to load
            page.wait_for_timeout(5000)

            # Debug: Check what's on the page
            print("[DEBUG] Checking page content...")
            page_html = page.content()
            if 'WhatsApp' in page_html:
                print("[DEBUG] WhatsApp page detected")
            else:
                print("[WARNING] May not be on WhatsApp page")

            # Try multiple selectors for chat list items
            chat_selectors = [
                'div[role="listitem"]',
                '[data-testid="cell-frame-container"]',
                'div[data-testid="chat"]',
                'div[class*="chat"]',
                'div[tabindex="-1"]'
            ]

            chats = []
            for selector in chat_selectors:
                chats = page.locator(selector).all()
                if chats and len(chats) > 0:
                    print(f"[INFO] Found {len(chats)} element(s) using selector: {selector}")
                    # Filter out non-chat elements (keep only those with reasonable size)
                    valid_chats = []
                    for chat in chats[:10]:  # Check first 10
                        try:
                            box = chat.bounding_box()
                            if box and box['height'] > 30:  # Chats are usually taller than 30px
                                valid_chats.append(chat)
                        except:
                            pass

                    if valid_chats:
                        chats = valid_chats
                        print(f"[INFO] Filtered to {len(chats)} valid chat(s)")
                        break

            if not chats or len(chats) == 0:
                print("[WARNING] No chats found - WhatsApp may not be fully loaded")
                print("[INFO] Check screenshot: " + str(screenshot_path))
                browser.close()
                return []

            # Process first 5 chats (they're usually sorted by recent activity)
            print(f"[INFO] Processing first {min(5, len(chats))} chat(s)...")

            # Process each chat
            for i, chat in enumerate(chats[:5]):  # Limit to 5 chats
                try:
                    print(f"[DEBUG] Processing chat {i+1}...")

                    # Click on the chat
                    chat.click()
                    page.wait_for_timeout(2000)

                    # Get sender name
                    sender_selectors = [
                        'header span[dir="auto"]',
                        'header div[role="button"] span',
                        'div[data-testid="conversation-header"] span',
                        'header span'
                    ]

                    sender = "Unknown"
                    for selector in sender_selectors:
                        sender_elem = page.locator(selector).first
                        if sender_elem.count() > 0:
                            try:
                                sender_text = sender_elem.inner_text()
                                if sender_text and len(sender_text) > 0:
                                    sender = sender_text
                                    break
                            except:
                                pass

                    print(f"[DEBUG] Chat name: {sender}")

                    # Get last message (incoming)
                    message_selectors = [
                        'div.message-in span.selectable-text',
                        'div[data-pre-plain-text] span.selectable-text',
                        'span[dir="ltr"].selectable-text',
                        'div[class*="message-in"] span'
                    ]

                    messages = []
                    for selector in message_selectors:
                        messages = page.locator(selector).all()
                        if messages:
                            print(f"[DEBUG] Found {len(messages)} messages with selector: {selector}")
                            break

                    if messages:
                        last_message = messages[-1]
                        message_text = last_message.inner_text()
                        message_id = f"{sender}_{message_text[:20]}"

                        print(f"[DEBUG] Last message: {message_text[:50]}...")

                        # Skip if already processed
                        if message_id in processed:
                            print(f"[DEBUG] Already processed, skipping")
                            continue

                        message_data = {
                            'sender': sender,
                            'message': message_text,
                            'time': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
                        }

                        print(f"[INFO] New message from: {sender}")

                        # Create task file
                        create_task_file(message_data)

                        # Mark as processed
                        processed.append(message_id)
                        new_messages.append(message_data)
                    else:
                        print(f"[DEBUG] No messages found in chat {i+1}")

                except Exception as e:
                    print(f"[WARNING] Failed to process chat {i+1}: {e}")
                    continue

            # Save processed list
            save_processed_messages(processed)

        except Exception as e:
            print(f"[ERROR] Failed to check messages: {e}")

        # Close browser
        browser.close()

        return new_messages


def watch_continuous(check_interval=300):
    """Watch WhatsApp continuously"""
    print(f"[INFO] WhatsApp Watcher started")
    print(f"[INFO] Checking every {check_interval} seconds")
    print(f"[INFO] Press Ctrl+C to stop")

    try:
        while True:
            print(f"\n[INFO] Checking WhatsApp at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
            new_messages = check_whatsapp()

            if new_messages:
                print(f"[SUCCESS] Processed {len(new_messages)} new message(s)")

            print(f"[INFO] Next check in {check_interval} seconds...")
            time.sleep(check_interval)

    except KeyboardInterrupt:
        print("\n[INFO] WhatsApp Watcher stopped by user")


def main():
    import argparse

    parser = argparse.ArgumentParser(description='WhatsApp Watcher - Monitor for new messages')
    parser.add_argument('--once', action='store_true', help='Check once and exit')
    parser.add_argument('--interval', type=int, default=300, help='Check interval in seconds (default: 300)')

    args = parser.parse_args()

    if args.once:
        print("[INFO] Running single check...")
        new_messages = check_whatsapp()
        if new_messages:
            print(f"[SUCCESS] Processed {len(new_messages)} new message(s)")
        else:
            print("[INFO] No new messages")
    else:
        watch_continuous(args.interval)


if __name__ == "__main__":
    main()
